---
- src: geerlingguy.apache
- src: geerlingguy.composer
- src: geerlingguy.firewall
- src: geerlingguy.git
- src: geerlingguy.java
- src: geerlingguy.mailhog
- src: geerlingguy.mysql
- src: geerlingguy.nodejs
- src: geerlingguy.php
- src: geerlingguy.php-mysql
- src: geerlingguy.php-pecl
- src: geerlingguy.php-xdebug
- src: geerlingguy.phpmyadmin
- src: geerlingguy.postfix
- src: geerlingguy.ruby
- src: http://github.com/idealista/tomcat-role.git
  scm: git
  version: 1.0.0
  name: idealista.tomcat